#!/bin/sh

# This script will compile or run another finishing operation on a document.
#
# Compiles LaTeX, R Markdown, Markdown, Java, C, C++ or runs interpreted languages
# Runs scripts based on extention or shebang
#
# Note that .tex files which you wish to compile with XeLaTeX should have the
# string "xelatex" somewhere in a comment/command in the first 5 lines.


file=$(readlink -f "$1")
dir=${file%/*}
base="${file%.*}"
ext="${file##*.}"

cd "$dir" || exit

textype() { \
	command="pdflatex"
	( sed 5q "$file" | grep -i -q 'xelatex' ) && command="xelatex"
	$command --output-directory="$dir" "$base" &&
	grep -i addbibresource "$file" >/dev/null &&
	biber --input-directory "$dir" "$base" &&
	$command --output-directory="$dir" "$base" &&
	$command --output-directory="$dir" "$base"
}

case "$ext" in
	[rR]md) Rscript -e "rmarkdown::render('$file', quiet=TRUE)" ;;
	tex) textype "$file" ;;
	md) pandoc "$file" --pdf-engine=xelatex -o "$base".pdf ;;
        java) javac "$file" ;;
	c) cc "$file" -o "$base" ;;
        cpp) g++ -std=c++11 -O2 -Wall "$file" -o "$base" ;;
	py) python3 "$file" ;;
        js) node "$file" ;;
        m) octave "$file" ;;
	*) sed 1q "$file" | grep "^#!/" | sed "s/^#!//" | xargs -r -I % "$file" ;;
esac
